import * as Joi from 'joi';

export const appConfig = {
  isGlobal: true,
  validationSchema: Joi.object({
    APP_ENV: Joi.string().required(),
    // PUBLIC_AI_API_BASE_URL: Joi.string().required(),
    // FRONTEND_BASE_URL: Joi.string().required(),
    MYSQL_DB_HOST: Joi.string().required(),
    MYSQL_DB_PORT: Joi.string().required(),
    MYSQL_DB_USERNAME: Joi.string().required(),
    // MYSQL_DB_PASSWORD: Joi.string().required(),
    MYSQL_DB_DATABASE: Joi.string().required(),
    MONGODB_URI: Joi.string().required(),
    // EMAIL_HOST: Joi.string().required(),
    // EMAIL_FROM: Joi.string().required(),
    // EMAIL_USER: Joi.string().required(),
    // EMAIL_PASSWORD: Joi.string().required(),
    // KEYCLOAK_BASE_URL: Joi.string().required(),
    // KEYCLOAK_REALM: Joi.string().required(),
    // KEYCLOAK_ADMIN_USERNAME: Joi.string().required(),
  }),
};

export enum ConfigKey {
  APP_ENV = 'APP_ENV',
  PUBLIC_AI_API_BASE_URL = 'PUBLIC_AI_API_BASE_URL',
  FRONTEND_BASE_URL = 'FRONTEND_BASE_URL',
  MYSQL_DB_HOST = 'MYSQL_DB_HOST',
  MYSQL_DB_PORT = 'MYSQL_DB_PORT',
  MYSQL_DB_USERNAME = 'MYSQL_DB_USERNAME',
  MYSQL_DB_PASSWORD = 'MYSQL_DB_PASSWORD',
  MYSQL_DB_DATABASE = 'MYSQL_DB_DATABASE',
  MONGODB_URI = 'MONGODB_URI',
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_FROM = 'EMAIL_USER',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
  KEYCLOAK_BASE_URL = 'KEYCLOAK_BASE_URL',
  KEYCLOAK_REALM = 'KEYCLOAK_REALM',
  KEYCLOAK_CLIENT_ID = 'KEYCLOAK_CLIENT_ID',
  KEYCLOAK_CLIENT_SECRET = 'KEYCLOAK_CLIENT_SECRET',
  KEYCLOAK_ADMIN_USERNAME = 'KEYCLOAK_ADMIN_USERNAME',
  KEYCLOAK_ADMIN_PASSWORD = 'KEYCLOAK_ADMIN_PASSWORD',
  KEYCLOAK_ADMIN_CLIENT_ID = 'KEYCLOAK_ADMIN_CLIENT_ID',
  KEYCLOAK_PUBLIC_KEY = 'KEYCLOAK_PUBLIC_KEY',
  RMQ_URL = 'RMQ_URL',
  RMQ_QUEUE = 'RMQ_QUEUE',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_CLUSTER_HOSTS = 'REDIS_CLUSTER_HOSTS',
  FILE_SERVER_ENDPOINT = 'FILE_SERVER_ENDPOINT',
}

export enum AppEnvironment {
  LOCAL = 'LOCAL',
  STAGE = 'DEV',
  TESTING = 'TESTING',
  PROD = 'PRODUCTION',
}
